# data parameters
model: Colorization
train_data_path: /home/yoon/Datasets/DNCNN

model_name: colorization
save_path: checkpoint/dncnn/
epoch: 20
batch_size: 8

# training parameters
cuda: True
gpu_ids: [0]  # set the GPU ids to use, e.g. [0] or [1, 2]
num_workers: 16
print_iter: 5000

load_path: checkpoint/unet/0.tar
input_size: 256
noise: gaussian
lr: 0.0001

hint: 2